config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :item_calendarios
  resources :lista
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  root 'pages#index'
  get 'index'  => 'pages#index'
  get 'curso' => 'pages#shop'
  get 'cliente' => 'pages#cliente'
  get 'conocenos' => 'pages#about'
  get 'calendario' => 'pages#calendario'
  post 'calendario' => 'pages#calendario'
  get 'programa' => 'pages#programa'
  get 'infocurso' => 'pages#infocurso'  
  get 'infoprograma' => 'pages#infoprograma'
  get 'conferencia' => 'pages#seminario'
  get 'capacitaciones' => 'pages#capacitaciones'
  get 'sedes' => 'pages#sedes'
  get 'identidad' => 'pages#identidad'
  get 'certificaciones' => 'pages#certificaciones'
  get 'contactenos' => 'contacts#new'
  get 'inscripcion' => 'pedidos#new'
  
  
  resources :infoprograma
  resources :infocurso
  resources :calendarios
  resources :item_calendarios
  resources :listas
  resources :pedidos
  resources :contacts, only: [:new, :create]

  

end

app/models/item_calendario.rb
class ItemCalendario < ActiveRecord::Base
  belongs_to :calendario
  belongs_to :lista
  belongs_to :pedido
  


  def total_precio

  	if calendario.curso.nil?
  		if calendario.programa.nil?
  			0
  		else
  			calendario.programa.precio
  		end
	else
			calendario.curso.precio
	end
		
	end
end

app/controllers/item_calendarios_controller.rb
class ItemCalendariosController < ApplicationController

  include CurrentLista
	before_action :set_lista, only: [:create]
	before_action :set_item_calendario, only: [:show, :destroy]

def create
	calendario = Calendario.find(params[:calendario_id])
	@item_calendario = @lista.add_calendario(calendario.id)
	if @item_calendario.save
		redirect_to root_url, notice: 'Curso(s) Agregado al registro de Inscripción'

	else

		render :new
	end
	
end

	private

	def set_item_calendarios
		@item_calendario = ItemCalendario.find(params[:calendario_id])

	end

def item_calendario_params
	params.require(:item_calendario).permit(:calendario_id)
end

end

app/helpers/item_calendarios_helper.rb
module ItemCalendariosHelper
end

app/views/item_calendarios/_form.html.erb
<%= form_for(@item_calendario) do |f| %>
  <% if @item_calendario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_calendario.errors.count, "error") %> prohibited this item_calendario from being saved:</h2>

      <ul>
      <% @item_calendario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :calendario_id %><br>
    <%= f.text_field :calendario_id %>
  </div>
  <div class="field">
    <%= f.label :lista %><br>
    <%= f.text_field :lista %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_calendarios/edit.html.erb
<h1>Editing Item Calendario</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_calendario %> |
<%= link_to 'Back', item_calendarios_path %>

app/views/item_calendarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Calendarios</h1>

<table>
  <thead>
    <tr>
      <th>Calendario</th>
      <th>Lista</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_calendarios.each do |item_calendario| %>
      <tr>
        <td><%= item_calendario.calendario %></td>
        <td><%= item_calendario.lista %></td>
        <td><%= item_calendario.cantidad %></td>
        <td><%= link_to 'Show', item_calendario %></td>
        <td><%= link_to 'Edit', edit_item_calendario_path(item_calendario) %></td>
        <td><%= link_to 'Destroy', item_calendario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item calendario', new_item_calendario_path %>

app/views/item_calendarios/new.html.erb
<h1>New Item Calendario</h1>

<%= render 'form' %>

<%= link_to 'Back', item_calendarios_path %>

app/views/item_calendarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calendario:</strong>
  <%= @item_calendario.calendario %>
</p>

<p>
  <strong>Lista:</strong>
  <%= @item_calendario.lista %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @item_calendario.cantidad %>
</p>

<%= link_to 'Edit', edit_item_calendario_path(@item_calendario) %> |
<%= link_to 'Back', item_calendarios_path %>