config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :item_calendarios
  resources :lista
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  root 'pages#index'
  get 'index'  => 'pages#index'
  get 'curso' => 'pages#shop'
  get 'cliente' => 'pages#cliente'
  get 'conocenos' => 'pages#about'
  get 'calendario' => 'pages#calendario'
  post 'calendario' => 'pages#calendario'
  get 'programa' => 'pages#programa'
  get 'infocurso' => 'pages#infocurso'  
  get 'infoprograma' => 'pages#infoprograma'
  get 'conferencia' => 'pages#seminario'
  get 'capacitaciones' => 'pages#capacitaciones'
  get 'sedes' => 'pages#sedes'
  get 'identidad' => 'pages#identidad'
  get 'certificaciones' => 'pages#certificaciones'
  get 'contactenos' => 'contacts#new'
  get 'inscripcion' => 'pedidos#new'
  
  
  resources :infoprograma
  resources :infocurso
  resources :calendarios
  resources :item_calendarios
  resources :listas
  resources :pedidos
  resources :contacts, only: [:new, :create]

  

end

app/views/shared/_buscador.html.erb
<%= form_tag root_path, method: :get do %>
<p>
<%= render 'shared/message' %>
    <%= text_field_tag( :search, value = nil , options = {:size => "300", :placeholder => "Buscar Cursos o Eventos (Excel, Microsoft, Project)", :class => "form-validate" }) %>
      <%= submit_tag "Buscar", curso: nil %>
  </p>
<% end %>
<!--Fin de Buscador-->

app/views/shared/_contact_errors.html.erb
<% unless @contact.errors.empty? %>
	<script type="text/javascript">
		<% @contact.errors.full_messages.each do |msg| %>
	     	 toastr.error('<%= msg %>' )
		<% end %>
	</script>		
<% end %>

app/views/shared/_footer.html.erb
    <div class=" on-page">
      <%= image_tag('banner-footer2.jpg',  class: 'background-image', alt:'Background') %>
    </div>
	<footer class="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-8 col-md-offset-2">
							<ul class="footer-navigation">
								<li class="active"><%= link_to 'Home', root_path %></li>
								<li><%= link_to 'Nosotros', conocenos_path %></li>
								<li><%= link_to 'Programas', programa_path %></li>
								<li><%= link_to 'Cursos', curso_path %></li>
						        <li><%= link_to 'Conferencias', conferencia_path %></li>
								<li><%= link_to 'Contáctenos', contactenos_path %></li>
							</ul>

							</div>
							<ul class="accepted-payments">
							
								<div class="col-md-6 col-md-offset-4 side-social" align="center">
									
									<a class="col-md-2 col-md-offset-1" href="https://www.facebook.com/cecespolec/"  target="_blank"><%= image_tag('logitos-16.png') %></a>
									<a class="col-md-2 col-md-offset-0" href="https://twitter.com/cecespol" target="_blank"><%= image_tag('logitos-15.png') %></a>
									<!--<a href="#"><i class="fa fa-google-plus"></i></a>
									<a href="#"><i class="fa fa-pinterest"></i></a>
									<a href="#"><i class="fa fa-instagram"></i></a>-->
									<a class="col-md-2 col-md-offset-0" href="https://ec.linkedin.com/in/educonespol" target="_blank"><%= image_tag('logitos-14.png') %></i></a>
								</div>
							</ul>
							<div class="copyright">
								<p>Copyright © 2017 CEC - ESPOL.</p>
							</div>
						</div>
					</div><!-- /.row -->
				</div>
			</footer>

app/views/shared/_header.html.erb
<!-- Off screen navigation -->
    <div id="sidr">
		<ul>	
			<li>
			  <%= link_to '#', class: "side-logo" do %>
			    CEC
		    <% end %>
			</li>
			<li class="active"><%= link_to 'Home', root_path %></li>
			<li class="active"><%= link_to 'Programas', programa_path %></li>
			<li class="active"><%= link_to 'Cursos', curso_path %></li>
			<li class="active"><%= link_to 'Corporativas', capacitaciones_path %></li>
			<li class="active"><%= link_to 'Conferencias', conferencia_path %></li>
			<li class="active"><%= link_to 'Agenda', calendario_path %></li>
			
		</ul>

			<div class="side-social-menu-der">
				<a href="#"><i class="face fa-facebook"></i></a>
				<a href="#"><i class="face fa-twitter"></i></a>
				<a href="#"><i class="face fa-linkedin"></i></a>
			</div>
		</div>
		

		
			<nav class="navbar navbar-default">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">

						<a class="navbar-brand"><%= image_tag("logo3.png", class: "img-responsive") %><span class="logo-dot accent-bg"></span></a>

						<!--<a class="navbar-brand" href="index.html">CEC Espol<span class="logo-dot accent-bg"></span></a>-->
						
						<a href="#sidr" class="side-menu-opener mobile">
							<div class="bars">
						        <span class="bar top"></span>
						        <span class="bar middle"></span>
						        <span class="bar bottom"></span>
						    </div>
						</a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="collapse-navigation">
						<ul class="nav navbar-nav">

							<li>
							<%= link_to  root_path do %>
							<i class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"></i> HOME </a>
							<% end %>
							</li>

							<!--<li><%= link_to 'Nosotros', conocenos_path %></li>-->

							<li class="dropdown">
								<a href="./catalog.html" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Nosotros <span class="fa fa-angle-down"></span></a>
								<ul class="dropdown-menu">
									<li><%= link_to 'Conócenos', conocenos_path %></li>
									<li><%= link_to 'Nuestras Sedes', sedes_path %></li>
									<li><%= link_to 'Nuestra Identidad', identidad_path %></li>
								</ul>
							</li>


							<!--<li><%= link_to 'Cursos', curso_path %></li>-->
							<li class="dropdown">
							    <a href="./catalog.html" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Servicios <span class="fa fa-angle-down"></span></a>
							    <ul class="dropdown-menu">
							      
							      	<li><%= link_to 'Programas', programa_path %></li>
							      	<li><%= link_to 'Cursos', curso_path %></li>
							      	<li><%= link_to 'Capacitaciones Corporativas', capacitaciones_path %></li>
							      	<li><%= link_to 'Conferencias', conferencia_path %></li>
							      	<li><%= link_to 'Agenda de Eventos', calendario_path %></li>      	
							    </ul>
							</li>

							<li><%= link_to 'Clientes', cliente_path %></li>
						<li>
							<%= link_to  contactenos_path do %>
							<i class="fa fa-paper-plane"></i> Contáctenos</a>
							<% end %>
						</li>

						<li>
							<% if @lista.nil? %>

								<a href="#" class="menu-cart"><i class="fa fa-shopping-cart"></i> $0.00</a>
							<% end %>
							<% else %>
									<%= link_to  @lista,  class: 'menu-cart'  do %>
									<class="menu-cart"> <i class="fa fa-shopping-cart"></i>
									<%= number_to_currency  @lista.total_precio  %>
								<% end %>
						</li>		

					</ul>

			<ul class="nav navbar-nav navbar-right">
							<li>
								<a href='index' class="side-menu-opener">
									<div class="bars">
								        <span class="bar top"></span>
								        <span class="bar middle"></span>
								        <span class="bar bottom"></span>
								    </div>
								</a>
						  </li>
			</ul>

			<div class="side-social-header hidden-md hidden-sm" align="right">
				
				<a href="https://www.facebook.com/cecespolec/"  target="_blank"><i class="face1 fa-facebook"></i></a>
				<a href="https://twitter.com/cecespol" target="_blank"><i class="face1 fa-twitter"></i></a>
				<!--<a href="#"><i class="fa fa-google-plus"></i></a>
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-instagram"></i></a>-->
				<a href="https://ec.linkedin.com/in/educonespol" target="_blank"><i class="face1 fa-linkedin"></i></a>
			</div>
					</div><!-- /.navbar-collapse -->
				</div><!-- /.container -->
			</nav>





						

app/views/shared/_list.html.erb
<!-- PROGRAMAS -->
<BR> 

<div class="background-div">
    <Br>Programas</Br><br>
</div>  
			<section class="products-grid">
				<div class="container">
					<div class="row products-container">
					<% @count = 0 %>
					<% @programas.order("RAND()").each do |programa| %>
						<%if @count < 3 %>
							<% @count = @count + 1 %>  
							<div class="col-md-4 col-sm-6 col-xs-12 product">
								<div class="thumbnail" style="background-image: url('/assets/products/<%= programa.imagen_file_name %>');">
								<%= image_tag programa.imagen %>
								<div class="product-details text-center">
										<div class="align-vertical">
											<h3><%= programa.titulo %></h3>
											<%= link_to  infoprograma_path(programa_id: programa), class: "btn btn-primary"  do %>
			  								<i class="fa fa-shopping-cart"></i> Más información
			  								<% end %>
										</div>
									</div>
									
								</div>
							</div>
						<% else %>
						<% break %>
						 <% end %>
					 <% end %>
					</div><!-- /.row -->
				</div><!-- /.container -->
				<a href="programa" class="vermas"><%= image_tag('mas.png')%></a>
			</section>
<!-- CURSOS -->
<div class="background-div">
            <BR>Cursos<BR><BR>
        </div>  
<section class="products-grid">
				<div class="container">
					<div class="row products-container">
					<% @count = 0 %>
					<% @cursos.order("RAND()").each do |curso| %>
					<%if @count < 3 %>
							<% @count = @count + 1 %>  
						<div class="col-md-4 col-sm-6 col-xs-12 product">
							<div class="thumbnail" style="background-image: url('/assets/products/<%= curso.image_file_name %>');">
							<%= image_tag curso.image %>
								<div class="product-details text-center">
									<div class="align-vertical">
										<h3><%= curso.titulo %></h3>
										<%= link_to  infocurso_path(curso_id: curso), class: "btn btn-primary"  do %>
		  								<i class="fa fa-shopping-cart"></i> Más información
		  								<% end %>
									</div>
								</div>
							</div>
						</div>
					<% else %>
						<% break %>
						 <% end %>
					 <% end %>
					</div><!-- /.row -->
				</div><!-- /.container -->
				<a href="curso" class="vermas"><%= image_tag('mas.png')%></a>
			</section>

			
			
			

app/views/shared/_message.html.erb
<%  unless flash.empty? %>
<script type="text/javascript"> 
<% flash.each do |f| %>
	<% type = f[0].to_s.gsub('alert', 'error' ).gsub('notice', 'info') %>
	toastr['<%= type %>'] ('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_msg.html.erb
<% unless @pedido.errors.empty? %>
	<script type="text/javascript">
		<% @pedido.errors.full_messages.each do |msg| %>
	     	 toastr.error('<%= msg %>' )
			

		<% end %>
	</script>		
<% end %>