config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :item_calendarios
  resources :lista
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  root 'pages#index'
  get 'index'  => 'pages#index'
  get 'curso' => 'pages#shop'
  get 'cliente' => 'pages#cliente'
  get 'conocenos' => 'pages#about'
  get 'calendario' => 'pages#calendario'
  post 'calendario' => 'pages#calendario'
  get 'programa' => 'pages#programa'
  get 'infocurso' => 'pages#infocurso'  
  get 'infoprograma' => 'pages#infoprograma'
  get 'conferencia' => 'pages#seminario'
  get 'capacitaciones' => 'pages#capacitaciones'
  get 'sedes' => 'pages#sedes'
  get 'identidad' => 'pages#identidad'
  get 'certificaciones' => 'pages#certificaciones'
  get 'contactenos' => 'contacts#new'
  get 'inscripcion' => 'pedidos#new'
  
  
  resources :infoprograma
  resources :infocurso
  resources :calendarios
  resources :item_calendarios
  resources :listas
  resources :pedidos
  resources :contacts, only: [:new, :create]

  

end

app/views/pages/certificaciones.html.erb
<br>
<br>
<br>
<br>
<br>
<div class="background-div">
         <BR>Certificaciones, Alianzas y Acreditaciones<BR><BR>
</div>
<div class="container">

</div>  
</br>
</br>
</br>

app/views/pages/cliente.html.erb
<br>
<br>
<br>
<br>
<br><div class="background-div">
         <BR>Nuestros Clientes<BR><BR>
</div>
<div class="container">

        <br>
        <br>
			<p style="text-align: justify;">Contamos con una cartera muy importante de clientes, en donde todos son relevantes. Siendo nuestro principal reto establecer y fortalecer un v&iacute;nculo a largo plazo, que represente un apoyo para hacer su negocio m&aacute;s productivo. 
			<br><br>Estas son algunas de las empresas que han confiado la capacitaci&oacute;n de su personal al CEC-ESPOL.</p>

             <%= image_tag('clientes.png', alt:'Clientes') %>
	</div>		<br>

app/views/pages/infocurso.html.erb
<br>
<br>
<br>
<br>
<br>
<div class="background-div">
         <BR><%= @infoc.titulo %><BR><BR>
</div>

<%= stylesheet_link_tag    'eventos', media: 'all', 'data-turbolinks-track' => true %>

<div class="container">  
    <div id="container" >     
        <div class="row">
            <div class="col-md-6">
                <br>       
                <br>
                <br>             
                <div align =center><%= image_tag @infoc.image%></div>
                <br>
                <br>
            </div>    
            <div class="col-md-6" style="margin-top: 55px;">
                <br>    
                <ul class="nav nav-tabs" class="col-xs6 col-md-4" >
                    <li class="active"><a data-toggle="tab" href="#home" style="font-size: 18px;">General</a></li>
                    <li><a data-toggle="tab" href="#menu1" style="font-size: 18px;">Contenido</a></li>
                </ul>
                <div class="tab-content" style="margin-left: 20px;">
                    <div id="home" class="tab-pane fade in active">
                    <div style="margin-right: 10px; margin-top: -10px;">
                                            <p style="text-align: justify;"><%= simple_format @infoc.descripccion %></p>
                        </div>
                          
                    </div>
                    <div id="menu1" class="tab-pane fade">
                    <div style="margin-right: 10px; margin-top: -10px;">
                         <p style="text-align: justify;"><%= simple_format @infoc.contenido %></p>
                    </div>
                          
                    </div>
                </div>
                <div style="margin-left: 210px;">
                <%= link_to "Regresar", curso_path, class: 'btn-regresar btn-default' %></div>
            </div>    
        </div>    
    </div>
    <div class="agenda-evento table-responsive" style="align-content: center;">
        <div>
          <br>
          <br>
            <table class="table table-condensed table-bordered">
                <thead>
                    <th colspan="3" class="agenda-th1"> 
                        <%= image_tag('calendario_prueba-08.png') %>Agenda
                    </th> 
                    <tr>
                        <th class="table-th1">Fecha</th>
                        <th class="table-th1">Horario</th>
                        <th class="table-th1">  </th>
                    </tr>
                </thead>
                    <tbody>
                                <!-- Single event in a single day -->

                        <% @n_eventos = 0 %>
                                
                        <% @calendarios.where("fecha_inicio >= ?", @fecha_actual).order("fecha_inicio").each do |calendario| %> 
                                <%if calendario.curso.nil? %>
                                <% else%>  
                                  <%if calendario.curso.id == @infoc.id %>
                                     <% @n_eventos = @n_eventos + 1 %>
                                    <tr>
                                        <td class="agendadateventos active" rowspan="1">                  
                                             <div class="dayofmontheventos"><%= calendario.fecha_inicio.strftime("%d") %> </div>
                                                <% if calendario.fecha_inicio.strftime("%A")=="Sunday" %> Domingo
                                                <% elsif calendario.fecha_inicio.strftime("%A")=="Monday" %> Lunes
                                                <% elsif calendario.fecha_inicio.strftime("%A")=="Tuesday" %> Martes
                                                <% elsif calendario.fecha_inicio.strftime("%A")=="Wednesday" %> Mi&eacutercoles
                                                <% elsif calendario.fecha_inicio.strftime("%A")=="Thursday" %> Jueves
                                                <% elsif calendario.fecha_inicio.strftime("%A")=="Friday" %> Viernes
                                                <% elsif calendario.fecha_inicio.strftime("%A")=="Saturday" %> S&aacutebado
                                                <% else %> 
                                                <% end %>
                                                <div class="dayofweekeventos">
                                                       <% if calendario.fecha_inicio.strftime("%B")=="January" %> Enero
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="February" %> Febrero
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="March" %> Marzo
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="April" %> Abril
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="May" %> Mayo
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="June" %> Junio
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="July" %> Julio
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="August" %> Agosto
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="September" %> Septiembre
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="October" %> Octubre
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="November" %> Noviembre
                                                             <% elsif calendario.fecha_inicio.strftime("%B")=="December" %> Diciembre
                                                             <% else %> 
                                                        <% end %>
                                                    </div>
                                            <div class="diaventos text-muted"> 
                                                    <%= calendario.fecha_inicio.year %>
                                                    </div>
                                                      </td> 

                                                        <% @registrado = false %>

                                                        <% @lista.item_calendarios.each do |item| %>
                                                            
                                                            <%if item.calendario.curso.nil? %>
                                                                
                                                            <%else%>
                                                                <%if item.calendario.curso.id == calendario.curso.id %>  
                                                                    <% @registrado = true %>  

                                                                <%end%>
                                                            <%end%>     
                                                        <%end%>

                                                        <td style= "width: 50px; text-align: center; vertical-align: middle;">
                                                        <div style="margin-top: 18px; margin-left: 10px; margin-right: 10px;"><%= calendario.fecha_inicio.strftime("%R") %></div> 
                                                        </td>
                                                          <td colspan="1" style="text-align: center; vertical-align: middle;" >
                                                            <%if @registrado == false %>  

                                                                 <%= button_to item_calendarios_path(calendario_id: calendario), class: 'btn-mas_informacion btn-default' do %>
                                                                 <i class="fa fa-shopping-cart"></i> Inscribirse
                                                                 <%end%>
                                                                
                                                            <% end %>
                                                    </td>
                                        </tr>   
                                                    <% else%>
                                                     <%end%>
                                                     <%end%>   
                                                 <% end %>

                          <%if @n_eventos == 0 %>
                              <th colspan="3"> 
                               <br>
                                  <div style="text-align: center;">No hay eventos agendados para el Curso <%= @infoc.titulo %></div><br>
                              </th> 
                          <% else%>
                          <%end%>  
                    </tbody>
            </table>
        </div>
    </div>
</body>
<br><br>

app/views/pages/infoprograma.html.erb
<br>
<br>
<br>
<br>
<br>
<div class="background-div">
         <BR><%= @infop.titulo %><BR><BR>
</div>

<%= stylesheet_link_tag    'eventos', media: 'all', 'data-turbolinks-track' => true %>

<div class="container">

    <div id="container" >     
        <div class="row">
            <div class="col-md-6">
                <br>       
                <br>
                <br>             
                <div align =center><%= image_tag @infop.imagen%></div>
                <br>
                <br>
            </div>    
            <div class="col-md-6" style="margin-top: 55px;">
                <br>    
                <ul class="nav nav-tabs" class="col-xs6 col-md-4" >
                    <li class="active"><a data-toggle="tab" href="#home" style="font-size: 18px;">General</a></li>
                    <li><a data-toggle="tab" href="#menu1" style="font-size: 18px;">Contenido</a></li>
                </ul>
                <div class="tab-content" style="margin-left: 15px;">
                    <div id="home" class="tab-pane fade in active">
                        <div style="margin-right: 10px; margin-top: 20px;">
                                            <p style="text-align: justify;">
                                                <%= @infop.descripcion %>
                                            </p>
                        </div>
                    </div>
                    <div id="menu1" class="tab-pane fade">
                        <div style="margin-right: 10px; margin-top: -10px;">
                          <p style="text-align: justify;"><%= simple_format @infop.contenido %></p>
                          </div>
                    </div>
                </div>
                <div style=" margin-left: 210px; margin-top: 30px;">
                <%= link_to "Regresar", programa_path, class: 'btn-regresar btn-default' %></div>
            </div>    
        </div>    
    </div>
 <div class="agenda-evento table-responsive" style="align-content: center;">
        <div>
            <table class="table table-condensed table-bordered">
                <thead>
                    <th colspan="3" class="agenda-th1"> 
                        <%= image_tag('calendario_prueba-08.png') %>Agenda
                    </th> 
                    <tr>
                        <th class="table-th1">Fecha</th>
                        <th class="table-th1">Horario</th>
                        <th class="table-th1"></th>                    
                    </tr>
                </thead>
                <tbody>   

                <% @n_eventos = 0 %>

                    <% @calendarios.where("fecha_inicio >= ?", @fecha_actual).order("fecha_inicio").each do |calendario| %> 
                                      
                         <%if calendario.programa.nil? %>

                        <% else%>  
                            <%if calendario.programa.id == @infop.id %>
                                <% @n_eventos = @n_eventos + 1 %>
                                <tr>
                                    <td class="agendadateventos active"  rowspan="1">
                                        <div class="dayofmontheventos"><%= calendario.fecha_inicio.strftime("%d") %> </div>
                                            <% if calendario.fecha_inicio.strftime("%A")=="Sunday" %> Domingo
                                            <% elsif calendario.fecha_inicio.strftime("%A")=="Monday" %> Lunes
                                            <% elsif calendario.fecha_inicio.strftime("%A")=="Tuesday" %> Martes
                                            <% elsif calendario.fecha_inicio.strftime("%A")=="Wednesday" %> Mi&eacutercoles
                                            <% elsif calendario.fecha_inicio.strftime("%A")=="Thursday" %> Jueves
                                            <% elsif calendario.fecha_inicio.strftime("%A")=="Friday" %> Viernes
                                            <% elsif calendario.fecha_inicio.strftime("%A")=="Saturday" %> S&aacutebado
                                                <% else %> 
                                            <% end %>
                                        <div class="dayofweekeventos">
                                            <% if calendario.fecha_inicio.strftime("%B")=="January" %> Enero
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="February" %> Febrero
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="March" %> Marzo
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="April" %> Abril
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="May" %> Mayo
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="June" %> Junio
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="July" %> Julio
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="August" %> Agosto
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="September" %> Septiembre
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="October" %> Octubre
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="November" %> Noviembre
                                            <% elsif calendario.fecha_inicio.strftime("%B")=="December" %> Diciembre
                                            <% else %> 
                                            <% end %>
                                        </div>
                                        <div class="diaventos text-muted"> 
                                            <%= calendario.fecha_inicio.year %>
                                        </div>
                                    </td>
                                    <td style= "width: 50px; text-align: center; vertical-align: middle;">
                                        <div style="margin-top: 18px; margin-left: 10px; margin-right: 10px;"><%= calendario.fecha_inicio.strftime("%R") %>
                                        </div> 
                                    </td>

                                    <% @registrado = false %>

                                                        <% @lista.item_calendarios.each do |item| %>
                                                            
                                                            <%if item.calendario.programa.nil? %>
                                                                
                                                            <%else%>
                                                                <%if item.calendario.programa.id == calendario.programa.id%>  
                                                                    <% @registrado = true %>  

                                                                <%end%>
                                                            <%end%>     
                                                        <%end%>

                                    <td colspan="1" style="text-align: center; vertical-align: middle;" >
                                        <%if @registrado == false %>  
                                            <%= button_to item_calendarios_path(calendario_id: calendario), class: 'btn-mas_informacion btn-default' do %>
                                                <i class="fa fa-shopping-cart"></i> Inscribirse
                                                <%end%>            
                                                <% end %>
                                    </td>
                                </tr>   
                            <% else%>
                            <%end%>
                        <%end%>   
                     <% end %>

                     <%if @n_eventos == 0 %>
                        <th colspan="3"> 
                         <br>
                            <div style="text-align: center;">No hay eventos agendados para el Programa <%= @infop.titulo %></div><br>
                        </th> 
                    <% else%>
                    <%end%>  
                </tbody>
            </table>
        </div>
    </div>
</body><br>

app/views/pages/programa.html.erb
<br>
<br>
<br>
<br>
<br>
<div class="background-div">
    <BR>Programas<BR><BR>
</div> 
<div class="container"> 
	<section class="product-list">
		<div class="container">
			<% @programas.order("RAND()").each do |programa| %>
				<div class="row">
					<div class="col-md-12">
						<div class="product">
							<div class="row">
								<div class="col-md-6 col-xs-12">
									<div class="thumbnail">
										<%= image_tag programa.imagen %>	
									</div>
								</div>
								<div class="col-md-5 col-md-offset-1">
									<div class="product-details">
										<h2 class="product-title" ><%= programa.titulo %></h2>
										<div style="margin-right: 14px;">
										<p style="text-align: justify;">
											<%= truncate(programa.descripcion, length: 180) %>
											<%= link_to 'Ver más información.', infoprograma_path(programa_id: programa)%>
										</p></div>
									</div>
								</div>
							</div><!-- /.row -->
						</div><!-- /.product -->
					</div>
				</div><!-- /.row -->
			<% end %>
			<%= paginate @programas %>
		</div>
	</section>
</div>

app/views/pages/seminario.html.erb
<br><br>
<br>
<br>
<br>
<br>
<div class="background-div">
    <BR>Conferencias<BR><BR>
</div>
<%= stylesheet_link_tag    'eventos', media: 'all', 'data-turbolinks-track' => true %>
    <div class="container">
    <section class="product-list">
        <div class="container">
            <% @seminarios.order("RAND()").each do |seminario| %>
                <div class="row">
                    <div class="col-md-12">
                        <div class="product">
                            <div class="row">
                                <div class="col-md-6 col-xs-12">
                                    <div class="thumbnail">
                                        <%= image_tag seminario.imagen %>   
                                    </div>
                                </div>
                                <div class="col-md-5 col-md-offset-1">
                                    <div class="product-details">
                                        <h2 class="product-title" style="font-size: 28px;" ><%= seminario.titulo %></h2>
                                        <div style="margin-right: 15px; margin-top: -10px; text-align: justify;">
                                             <p style="text-align: justify;"><%= simple_format seminario.descripcion %></p>
                                        </div>
                                    </div>
                                </div>
        <div class="agenda-evento table-responsive" style="align-content: center;">
                <div>
                <br>
                    <table class="table table-condensed table-bordered">
                        <thead>
                            <th colspan="3" class="agenda-th1"> 
                                <%= image_tag('calendario_prueba-08.png') %>Agenda          
                            </th> 
                            <tr>
                                <th class="table-th1">Fecha</th>
                                <th class="table-th1">Horario</th>
                                <th class="table-th1">  </th>  
                            </tr>           
                        </thead>
                            <tbody>
                                <% @n_eventos = 0 %>

                                    <% @calendarios.where("fecha_inicio >= ?", @fecha_actual).order("fecha_inicio").each do |calendario| %> 
                                      
                                    <%if calendario.seminario.nil? %>
                                    <% else%>  
                                        <%if calendario.seminario.id == seminario.id%>
                                            <% @n_eventos = @n_eventos + 1 %>
                                        <tr>
                                            <td class="agendadateventos active" rowspan="1">
                                                <div class="dayofmontheventos"><%= calendario.fecha_inicio.strftime("%d") %> 
                                                </div>
                                                <% if calendario.fecha_inicio.strftime("%A")=="Sunday" %> Domingo
                                                     <% elsif calendario.fecha_inicio.strftime("%A")=="Monday" %> Lunes
                                                     <% elsif calendario.fecha_inicio.strftime("%A")=="Tuesday" %> Martes
                                                     <% elsif calendario.fecha_inicio.strftime("%A")=="Wednesday" %> Mi&eacutercoles
                                                     <% elsif calendario.fecha_inicio.strftime("%A")=="Thursday" %> Jueves
                                                     <% elsif calendario.fecha_inicio.strftime("%A")=="Friday" %> Viernes
                                                     <% elsif calendario.fecha_inicio.strftime("%A")=="Saturday" %> S&aacutebado
                                                    <% else %> 
                                                    <% end %>
                                                <div class="dayofweekeventos">
                                                    <% if calendario.fecha_inicio.strftime("%B")=="January" %> Enero
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="February" %> Febrero
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="March" %> Marzo
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="April" %> Abril
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="May" %> Mayo
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="June" %> Junio
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="July" %> Julio
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="August" %> Agosto
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="September" %> Septiembre
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="October" %> Octubre
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="November" %> Noviembre
                                                    <% elsif calendario.fecha_inicio.strftime("%B")=="December" %> Diciembre
                                                    <% else %> 
                                                    <% end %>
                                                </div>
                                                <div class="diaventos text-muted">
                                                 <%= calendario.fecha_inicio.year %>
                                                </div>
                                            </td>

                                            <% @registrado = false %>

                                            <% @lista.item_calendarios.each do |item| %>
 
                                                <%if item.calendario.seminario.nil? %>
                                                    
                                                <%else%>
                                                    <%if item.calendario.seminario.id == calendario.seminario.id %>  
                                                        <% @registrado = true %>  

                                                    <%end%>

                                                <%end%>     
                                            <%end%>
                                            <td style= "width: 50px; text-align: center; vertical-align: middle;">
                                                <div style="margin-top: 18px; margin-left: 10px; margin-right: 10px;"><%= calendario.fecha_inicio.strftime("%R") %>
                                                </div> 
                                            </td>
                                            <td colspan="1" style="text-align: center; vertical-align: middle;" >
                                             <%if @registrado == false %>  

                                                        <%= button_to item_calendarios_path(calendario_id: calendario), class: 'btn-mas_informacion btn-default' do %>
                                                        <i class="fa fa-shopping-cart"></i> Inscribirse
                                                        <%end%>       
                                                   <% end %>
                                            </td> 
                                        </tr>   
                                        <% else%>
                                         <%end%>
                                         <%end%>   
                                     <% end %>
                                        <%if @n_eventos == 0 %>
                                            <th colspan="3"> 
                                             <br>
                                                <div style="text-align: center;">No hay eventos agendados para el Curso <%= @infoc.titulo %></div><br>
                                            </th> 
                                            <% else%>
                                            <%end%>  
                                </tbody>
                            </table>
                        </div>
                    </div>
                                    
                                
                            </div><!-- /.row -->
                        </div><!-- /.product -->
                    </div>
                </div><!-- /.row -->
            <% end %>
            <%= paginate @seminarios %>
        </div>
    </section>
</div>

app/views/pages/shop.html.erb
<br>
<br>
<br>
<br>
<br> 
<div class="background-div">
      <BR>Cursos<BR><BR>
   </div>  
<div class="container">
  
	<section class="product-list">
		<div class="container">
			<% @cursos.order("RAND()").each do |curso| %>
				<div class="row">
					<div class="col-md-12">
						<div class="product">
							<div class="row">
								<div class="col-md-6 col-xs-12">
									<div class="thumbnail">
										<%= image_tag curso.image %>	
									</div>
								</div>
								<div class="col-md-5 col-md-offset-1">
									<div class="product-details">
										<h2 class="product-title" ><%= curso.titulo %></h2>
										<div style="margin-right: 14px;">
										<p style="text-align: justify;">
											<%= truncate(curso.descripccion, length: 172) %>
											<%= link_to 'Ver más información.', infocurso_path(curso_id: curso)%>
										</p></div>
									</div>
								</div>
							</div><!-- /.row -->
						</div><!-- /.product -->
					</div>
				</div><!-- /.row -->
			<% end %>
			<%= paginate @cursos %>
		</div>
	</section>
</div>