config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :item_calendarios
  resources :lista
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  root 'pages#index'
  get 'index'  => 'pages#index'
  get 'curso' => 'pages#shop'
  get 'cliente' => 'pages#cliente'
  get 'conocenos' => 'pages#about'
  get 'calendario' => 'pages#calendario'
  post 'calendario' => 'pages#calendario'
  get 'programa' => 'pages#programa'
  get 'infocurso' => 'pages#infocurso'  
  get 'infoprograma' => 'pages#infoprograma'
  get 'conferencia' => 'pages#seminario'
  get 'capacitaciones' => 'pages#capacitaciones'
  get 'sedes' => 'pages#sedes'
  get 'identidad' => 'pages#identidad'
  get 'certificaciones' => 'pages#certificaciones'
  get 'contactenos' => 'contacts#new'
  get 'inscripcion' => 'pedidos#new'
  
  
  resources :infoprograma
  resources :infocurso
  resources :calendarios
  resources :item_calendarios
  resources :listas
  resources :pedidos
  resources :contacts, only: [:new, :create]

  

end

app/models/lista.rb
class Lista < ActiveRecord::Base
	has_many :item_calendarios,  dependent:  :destroy

	def add_calendario(calendario_id)

		current_item = item_calendarios.find_by(calendario_id: calendario_id)

		if current_item

			
		else
			current_item = item_calendarios.build(calendario_id: calendario_id)
		end
	current_item
	end

	def total_precio
		item_calendarios.to_a.sum{ |item| item.total_precio }
	end
	def remove_calendario(calendario_id)
		current_item = item_calendarios.find_by(calendario_id: calendario_id)
		if current_item
			current_item.cantidad =current_item.cantidad-1
		else
			current_item = item_calendarios.build(calendario_id: calendario_id)
		end
	current_item
	end
end

app/controllers/lista_controller.rb
class ListaController < ApplicationController

before_action :set_lista, only: [:show, :destroy]
	rescue_from ActiveRecord::RecordNotFound, with: :invalid_lista
	
	def new 
		@lista = Lista.new
	end

	def show

	end

	def destroy
	@lista.destroy if @lista.id == session[:lista_id]
	session[:lista_id] = nil

	redirect_to root_url, notice:  'Su Registro está incompleto'

	end

	private

	def set_lista
		@lista = Lista.find(params[:id])

	end

	def lista_params	
		params[:lista]
	end

	def invalid_registro
		logger_error  'Su Inscripción es invalida'
		redirect_to root_url, notice: 'Inscripción Invalida'

		

	end
end

app/helpers/lista_helper.rb
module ListaHelper
end

app/views/lista/_lista.html.erb
<% @lista.item_calendarios.each do |item| %>
	<ul>
		<li>
			<%= item.cantidad %>&times;<%= item.calendario.curso.titulo %>
			<%= number_to_currency item.total_precio %>
		</li>
	</ul>
<% end %>

app/views/lista/show.html.erb
<br>
<br>
<br>
<div class="background-div">
        <BR>Detalle de Inscripción <BR><BR>
  </div>
  <br>
  <br>
<div class="container">
    <div class="agenda">
        <div class="tab-content">
            <div id="todos" class="tab-pane fade in active">
                    <div class="table-responsive">
                        <table class="table table-condensed table-bordered">
                            <thead >
                                <tr>
                                    <th class="table-th">Evento<BR></th>
                                    <th class="table-th">Tipo<BR></th>              
                                    <th class="table-th">Descripcion<BR></th>
                                    <th class="table-th">Subtotal<BR></th>
                                </tr>
                            </thead>              
                            <tbody>
                            <%  @lista.item_calendarios.each do |item| %>
                             <%if item.calendario.curso.nil? %>

                                <%if item.calendario.programa.nil? %>
                                    <tr>
                                      <td class="tamaño_imagen">               
                                        <%=image_tag  item.calendario.seminario.imagen %>
                                      </td>
                                      <td class="agenda-events">
                                            <div class="capa-exterior">
                                              <div class="capa-interior">
                                                Seminario
                                              </div>
                                            </div>
                                    </td>
                                    <td class="agenda-events">
                                        <div class="capa-exterior">
                                              <div class="capa-interior">
                                                <%= item.calendario.seminario.titulo %>
                                              </div>
                                            </div>
                                    </td>
                                    <td class="agenda-events">
                                        <div class="capa-exterior">
                                              <div class="capa-interior">
                                                <%= number_to_currency item.total_precio %>
                                              </div>
                                            </div>
                                    </td>
                                </tr>
                              <%else%>
                                <tr>
                                    <td class="tamaño_imagen">               
                                          <%=image_tag  item.calendario.programa.imagen %>
                                    </td>
                                     <td class="agenda-events">
                                            <div class="capa-exterior">
                                              <div class="capa-interior">
                                                Programa
                                              </div>
                                            </div>
                                    </td>
                                    <td class="agenda-events">
                      <div class="capa-exterior">
                                              <div class="capa-interior">
                                                <%= item.calendario.programa.titulo %>
                                              </div>
                                            </div>
                                    </td>
                                    <td class="agenda-events">
                                        <div class="capa-exterior">
                                              <div class="capa-interior">
                                                <%= number_to_currency item.total_precio %>
                                              </div>
                                            </div>
                                    </td>

                                </tr>
                                <% end %> 
                        <%else%>
                                <!-- Single event in a single day -->
                                <tr>
                                    <td class="tamaño_imagen">               
                    <%=image_tag  item.calendario.curso.image %>
                                    </td>
                                     <td class="agenda-events">
                                            <div class="capa-exterior">
                                              <div class="capa-interior">
                                                Curso
                                              </div>
                                            </div>
                                    </td>
                                    <td class="agenda-events">
                      <div class="capa-exterior">
                                              <div class="capa-interior">
                                                <%= item.calendario.curso.titulo %>
                                              </div>
                                            </div>
                                    </td>
                                    <td class="agenda-events">
                                        <div class="capa-exterior">
                                              <div class="capa-interior">
                                                <%= number_to_currency item.total_precio %>
                                              </div>
                                            </div>
                                    </td>
                                </tr>
                                 <% end %>

                                <% end %>    
                            </tbody>
                        </table>
                    </div>
                </p>
            </div>            
    <br>    
    <h3 style="text-align: right;">Total: <%= number_to_currency @lista.total_precio %></h3>
    </div>  
</div>
<br>


                <div class="container">
                    <div class="row">
                    <div class="col-xs-6 col-md-2"></div>
                        <div class="col-xs-6 col-md-8">
                              <div align="center">
                                    
                                    <div class="col-xs-6 col-md-4">
                                        <%= link_to "Volver", curso_path, class: 'btn-mas_informacion btn-default' %>
                                    </div>
                                    <div class="col-xs-6 col-md-4">
                                
                                         <%= link_to 'Cancelar', @lista, method: :delete, data: {confirm: 'Estas Seguro de eliminar tu registro' } , class: 'btn-mas_informacion btn-default'  %>
                                    </div>
                                    <div class="col-xs-6 col-md-4">
                                    <%= link_to'Registrar', inscripcion_path, method: :get , class: 'btn-mas_informacion btn-default'%>
                                    </div>
                                </div>
                        </div>
                    </div><!-- /.row -->

                </div>
        </div>
        <br>
<br>
<br>